/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 Light Theme
        'md-light': {
          primary: '#1976D2',
          'primary-container': '#D3E4FD',
          'on-primary': '#FFFFFF',
          'on-primary-container': '#001B3F',
          secondary: '#4CAF50',
          'secondary-container': '#C8E6C9',
          'on-secondary': '#FFFFFF',
          'on-secondary-container': '#0D2818',
          tertiary: '#9C27B0',
          'tertiary-container': '#F3E5F5',
          'on-tertiary': '#FFFFFF',
          'on-tertiary-container': '#4A148C',
          error: '#D32F2F',
          'error-container': '#FFEBEE',
          'on-error': '#FFFFFF',
          'on-error-container': '#8B0000',
          background: '#FEFBFF',
          'on-background': '#1A1C1E',
          surface: '#FEFBFF',
          'surface-variant': '#E1E2EC',
          'surface-container': '#F0F0F0',
          'surface-container-high': '#E8E8E8',
          'surface-container-highest': '#E0E0E0',
          'on-surface': '#1A1C1E',
          'on-surface-variant': '#43474E',
          outline: '#73777F',
          'outline-variant': '#C3C6CF',
        },
        // Material Design 3 Dark Theme
        'md-dark': {
          primary: '#90CAF9',
          'primary-container': '#0D47A1',
          'on-primary': '#003258',
          'on-primary-container': '#D3E4FD',
          secondary: '#81C784',
          'secondary-container': '#1B5E20',
          'on-secondary': '#0F3D14',
          'on-secondary-container': '#C8E6C9',
          tertiary: '#CE93D8',
          'tertiary-container': '#6A1B9A',
          'on-tertiary': '#4A148C',
          'on-tertiary-container': '#F3E5F5',
          error: '#EF5350',
          'error-container': '#C62828',
          'on-error': '#690005',
          'on-error-container': '#FFEBEE',
          background: '#1A1C1E',
          'on-background': '#E2E2E5',
          surface: '#1A1C1E',
          'surface-variant': '#43474E',
          'surface-container': '#1E1E1E',
          'surface-container-high': '#2A2A2A',
          'surface-container-highest': '#363636',
          'on-surface': '#E2E2E5',
          'on-surface-variant': '#C3C6CF',
          outline: '#8D9199',
          'outline-variant': '#43474E',
        },
      },
      fontFamily: {
        sans: [
          'Segoe UI',
          'Roboto',
          '-apple-system',
          'BlinkMacSystemFont',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          'Consolas',
          'Monaco',
          'Courier New',
          'monospace',
        ],
      },
      borderRadius: {
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
      },
      boxShadow: {
        'md-1': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'md-2': '0 2px 6px 0 rgb(0 0 0 / 0.1)',
        'md-3': '0 4px 12px 0 rgb(0 0 0 / 0.12)',
        'md-4': '0 8px 24px 0 rgb(0 0 0 / 0.15)',
        'md-5': '0 12px 36px 0 rgb(0 0 0 / 0.18)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
